language: java
jdk: openjdk8
install :
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -DbatchAnswers=n
script:
  - mvn install
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
